name: Check if should build images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'     
        required: true
        default: '3.14.0'
env:
  SNAPCRAFT_REPO: RocketChat/rocketchat-server-snap
  TESTS_REPO: RocketChat/rocketchat-release-tests
jobs:
  verify_release:
    runs-on: ubuntu-18.04
    steps:
      - name: Parse environment variables
        run: |
          if [[ -n "${{ github.event.release.tag_name }}" ]]; then
            export ROCKETCHAT_VERSION=${{ github.event.release.tag_name }}
          else
            export ROCKETCHAT_VERSION=${{ github.event.inputs.release }}
          fi

      - name: "Check if release candidate"
        run: |
          [[ -z "$(echo ${{ env.ROCKETCHAT_VERSION }} | grep rc)" ]]