name: Create cloud images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the packer install and test
        uses: ./.github/actions/packer
        with:
          do_token: ${{ secrets.do_token }}
          awk_key_id: ${{ secrets.awk_key_id }}
          awk_secret_key: ${{ secrets.awk_secret_key }}
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Packer image build*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#general'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
