name: Create release images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # release_cloud:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run the packer install and test
  #       uses: ./.github/actions/packer
  #       with:
  #         rocketchat_version: '${{ github.event.release.tag_name }}'
  #         do_token: ${{ secrets.do_token }}
  #         aws_key_id: ${{ secrets.aws_key_id }}
  #         aws_secret_key: ${{ secrets.aws_secret_key }}
  #     - name: Rocket.Chat Notification
  #       uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
  #       if: always()
  #       with:
  #         type: ${{ job.status }}
  #         job_name: '*Packer image build*'
  #         mention: 'here'
  #         mention_if: 'failure'
  #         url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
  
  release_snap:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1.2.0
        with:
          snapcraft_token: ${{ secrets.snapcraft_login }}
      - name: Checkout main Rocket.Chat repo
        uses: actions/checkout@v2
        with: 
          path: 'Rocket.Chat'
          ref: '${{ github.event.release.tag_name }}'
      - name: "Run snapcraft build"
        working-directory: "./snapcraft"
        run: |
          # snapcraft remote-build --build-on=amd64,arm64,armhf --launchpad-accept-public-upload
          sg lxd -c 'snapcraft snap --use-lxd'
      
      
