name: Create cloud images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the packer install and test
        uses: ./.github/actions/packer
        with:
          do_token: ${{ secrets.do_token }}
