name: Create release cloud images

on:
  release:
    types: [published]


jobs:
  release_cloud:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Parse environment variables
        run: |
          export ROCKETCHAT_VERSION=${{ github.event.release.tag_name }}
          echo "ROCKETCHAT_VERSION=$ROCKETCHAT_VERSION" >> $GITHUB_ENV
          [[ -z "$(echo ${{ env.ROCKETCHAT_VERSION }} | grep rc)" ]] && echo "CANDIDATE=false" >> $GITHUB_ENV

      - name: Run the packer install and test
        uses: RocketChat/rocketchat-packer@mainZZ
        if: env.CANDIDATE == 'false'
        with:
          rocketchat_version: '${{ env.ROCKETCHAT_VERSION }}'
          do_token: ${{ secrets.do_token }}
          aws_key_id: ${{ secrets.aws_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_key }}
      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: env.CANDIDATE == 'false'
      #   with:
      #     type: ${{ job.status }}
      #     job_name: '*Packer image build* - [DO Marketplace](https://marketplace.digitalocean.com/vendorportal/5cbf905da6e1a17be804b006/32/edit)'
      #     mention: 'here'
      #     mention_if: 'failure'
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
