name: Create release cloud images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'     
        required: true
        default: '3.14.0'
jobs:
  release_cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse environment variables
        run: |
          if [[ -n "${{ github.event.release.tag_name }}" ]]; then
            export ROCKETCHAT_VERSION=${{ github.event.release.tag_name }}
          else
            export ROCKETCHAT_VERSION=${{ github.event.inputs.release }}
          fi
      - name: Run the packer install and test
        uses: r0zbot/packer-action
        with:
          rocketchat_version: '${{ env.ROCKETCHAT_VERSION }}'
          do_token: ${{ secrets.do_token }}
          aws_key_id: ${{ secrets.aws_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_key }}
      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: '*Packer image build*'
      #     mention: 'here'
      #     mention_if: 'failure'
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
